# Generated by Django 5.1.3 on 2024-11-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='about_us_image')),
                ('link', models.CharField(max_length=999)),
                ('oder', models.IntegerField()),
                ('text', models.TextField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='admin_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouct_name', models.CharField(max_length=70)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_videos', models.FileField(upload_to='product_video')),
                ('description', models.TextField()),
                ('key_featurs_name', models.CharField(max_length=70)),
                ('key_featurs_image', models.ImageField(upload_to='key_featurs_image')),
                ('key_featurs_description', models.CharField(max_length=780)),
                ('Specification', models.TextField()),
                ('e_bonchers_feature_name', models.CharField(max_length=780)),
                ('e_bonchers_feature_image', models.ImageField(upload_to='e_bonchers_feature_image')),
                ('applications', models.TextField()),
                ('warranty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('feature_on_home', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=122)),
                ('answer', models.CharField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('showroom_address', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='footer_logos/')),
                ('website_linked_email_addresses', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=70)),
            ],
        ),
    ]
