# Generated by Django 5.1.3 on 2024-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('began_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersetting',
            name='contact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
