# Generated by Django 5.1.3 on 2024-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('began_admin', '0002_footersetting_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersetting',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
